### Configuration Files ###
spring.config.import=optional:.env[.properties]

### Spring Boot Application ###
spring.application.name=backend
server.port=8080

### Debugging ###
# logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
# logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE